In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv('shop_data.csv')
df

age  income  gender m_status buys
0   25   40000    Male   Single  Yes
1   34   60000  Female  Married   No
2   45  120000  Female   Single  Yes
3   23   32000    Male  Married   No
4   54  100000    Male  Married  Yes
5   35   72000  Female   Single   No
6   52  115000    Male  Married  Yes
7   46   85000  Female   Single   No
8   33   54000  Female  Married  Yes
9   29   47000    Male   Single   No

In [3]:
x = df.drop('buys', axis=1)
x

age  income  gender m_status
0   25   40000    Male   Single
1   34   60000  Female  Married
2   45  120000  Female   Single
3   23   32000    Male  Married
4   54  100000    Male  Married
5   35   72000  Female   Single
6   52  115000    Male  Married
7   46   85000  Female   Single
8   33   54000  Female  Married
9   29   47000    Male   Single

In [4]:
y = df.buys
y

0    Yes
1     No
2    Yes
3     No
4    Yes
5     No
6    Yes
7     No
8    Yes
9     No
Name: buys, dtype: object

In [5]:
from sklearn.preprocessing import LabelEncoder

In [8]:
le = LabelEncoder()
x = x.apply(le.fit_transform)
x

age  income  gender  m_status
0    1       1       1         1
1    4       4       0         0
2    6       9       0         1
3    0       0       1         0
4    9       7       1         0
5    5       5       0         1
6    8       8       1         0
7    7       6       0         1
8    3       3       0         0
9    2       2       1         1

In [9]:
from sklearn.model_selection import train_test_split
X_train, x_test, Y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=2)

In [10]:
X_train

age  income  gender  m_status
0    1       1       1         1
7    7       6       0         1
2    6       9       0         1
3    0       0       1         0
6    8       8       1         0
9    2       2       1         1
8    3       3       0         0

In [11]:
Y_train

0    Yes
7     No
2    Yes
3     No
6    Yes
9     No
8    Yes
Name: buys, dtype: object

In [12]:
x_test

age  income  gender  m_status
4    9       7       1         0
1    4       4       0         0
5    5       5       0         1

In [13]:
y_test

4    Yes
1     No
5     No
Name: buys, dtype: object

In [14]:
from sklearn.tree import DecisionTreeClassifier
dect = DecisionTreeClassifier()
dect.fit(X_train,Y_train)

DecisionTreeClassifier()

In [17]:
dect.predict(x_test)

array(['Yes', 'Yes', 'No'], dtype=object)

In [18]:
dect.score(x_test, y_test)

0.6666666666666666

In [19]:
## cross validation

In [40]:
from sklearn.model_selection import cross_val_score

In [42]:
result = cross_val_score(DecisionTreeClassifier(),x,y,cv=5)
result

array([0. , 0.5, 0.5, 1. , 0. ])

In [43]:
result.mean()

0.4

In [44]:
from sklearn.linear_model import LogisticRegression

In [45]:
result = cross_val_score(LogisticRegression(), x,y,cv=5)
result

array([0.5, 0. , 0.5, 0.5, 0.5])

In [46]:
result.mean()

0.4

In [47]:
from sklearn.linear_model import LinearRegression

In [50]:
result = cross_val_score(LinearRegression(), x,y,cv=4)
result

C:\Users\TAREQ\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\TAREQ\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\TAREQ\anaconda3\lib\site-packages\sklearn\linear_model\_base.py", line 505, in fit
    X, y = self._validate_data(X, y, accept_sparse=['csr', 'csc', 'coo'],
  File "C:\Users\TAREQ\anaconda3\lib\site-packages\sklearn\base.py", line 432, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "C:\Users\TAREQ\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "C:\Users\TAREQ\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 810, in check_X_y
    y = y.astype(np.float64)
ValueEr

array([nan, nan, nan, nan])